"""removed not nullable constraint on line breaks

Revision ID: 2f8ab80c138a
Revises: acfc1f667628
Create Date: 2022-10-14 21:31:22.700514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8ab80c138a'
down_revision = 'acfc1f667628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    with op.batch_alter_table('current_unsaved_poem', schema=None) as batch_op:
        batch_op.alter_column('current_line_breaks',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_unsaved_poem', schema=None) as batch_op:
        batch_op.alter_column('current_line_breaks',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
