"""Added unsaved tables

Revision ID: 4c93ffaf1f7c
Revises: ed8bf86fcc46
Create Date: 2022-10-17 01:41:54.357990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c93ffaf1f7c'
down_revision = 'ed8bf86fcc46'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('current_unsaved_poem_lines',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=True),
    # sa.Column('line_num', sa.String(), nullable=False),
    # sa.Column('line_text', sa.String(), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # # op.drop_table('sqlite_sequence')
    # with op.batch_alter_table('current_unsaved_poem', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('current_rhyme_scheme', sa.String(), nullable=False))
    #     batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_unsaved_poem', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('current_rhyme_scheme')

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('current_unsaved_poem_lines')
    # ### end Alembic commands ###
