"""empty message

Revision ID: 880cb7e12654
Revises: e80e26a82787
Create Date: 2022-10-27 21:14:39.007473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880cb7e12654'
down_revision = 'e80e26a82787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    with op.batch_alter_table('current_unsaved_poem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rhyme_scheme', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('rhymes', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('line_break', sa.Integer(), nullable=False))
        batch_op.drop_column('current_rhyme_scheme')
        batch_op.drop_column('current_title')
        batch_op.drop_column('current_line_breaks')
        batch_op.drop_column('current_rhymes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_unsaved_poem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_rhymes', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('current_line_breaks', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('current_title', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('current_rhyme_scheme', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('line_break')
        batch_op.drop_column('title')
        batch_op.drop_column('rhymes')
        batch_op.drop_column('rhyme_scheme')

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
