"""Added CurrentUnsavedPoem table and removed curr rhymes from user table

Revision ID: acfc1f667628
Revises: ce80e6832913
Create Date: 2022-10-14 21:01:22.096744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acfc1f667628'
down_revision = 'ce80e6832913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('current_unsaved_poem',
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('current_rhymes', sa.String(), nullable=False),
    # sa.Column('current_line_breaks', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('user_id')
    # )
    # op.drop_table('sqlite_sequence')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('current_rhymes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_rhymes', sa.VARCHAR(), nullable=True))

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('current_unsaved_poem')
    # ### end Alembic commands ###
