"""change curr rhyme scheme to curr rhymes

Revision ID: ce80e6832913
Revises: de6ed68000b0
Create Date: 2022-10-14 18:58:34.501633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce80e6832913'
down_revision = 'de6ed68000b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_rhymes', sa.String(), nullable=True))
        batch_op.drop_column('current_rhyme_scheme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_rhyme_scheme', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('current_rhymes')

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
