"""adde current title

Revision ID: e80e26a82787
Revises: 4c93ffaf1f7c
Create Date: 2022-10-21 19:57:49.070936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80e26a82787'
down_revision = '4c93ffaf1f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    with op.batch_alter_table('current_unsaved_poem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_title', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_unsaved_poem', schema=None) as batch_op:
        batch_op.drop_column('current_title')

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
